remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Bo Hao's Data Science Portfolio
description: This page is meant to serve as a portfolio for all my projects.